### PR TITLE
Update native-modules-setup.md

### PR DESCRIPTION
**Pull request by stratospheres**
Fixed a broken link to the "project structure" docs. Had ".md" tacked on the end, which was the problem.

### CODE REVIEW

**Comment by stratospheres** [comment]
Appears that the "check for broken links" step in CI is broken. Doesn't understand that the .md links don't really need the .md part in the URL. Given what I'm seeing here, this might indicate that other .md links throughout the docs are broken too, unless I'm missing something.

**Comment by chrisglein** [comment]
> Appears that the "check for broken links" step in CI is broken. Doesn't understand that the .md links don't really need the .md part in the URL. Given what I'm seeing here, this might indicate that other .md links throughout the docs are broken too, unless I'm missing something.

@asklar Can you look into the broken link issue?

**Comment by asklar** [comment]
The link with the .md is the correct one. The one without gives a 404

**Comment by jonthysell** [comment]
The check is operating as expected - .md is required https://github.com/microsoft/react-native-windows/blob/master/docs/project-structure is a dead link.

**Comment by stratospheres** [comment]
That's weird. It definitely was 404 *with the .md* before, and 200 without it, as my change suggests. It seems that @chrisglein saw the same thing (or at least I think so, given the PR approval). 

Did something change with the hosting? I'm 100% sure that this wasn't the behavior at that point...

**Comment by stratospheres** [comment]
Maybe germane to the question, maybe not...

image

**Pull request closed without merging**
