### PR TITLE
Versioned 0.64 docs

### PR DESCRIPTION
**Pull request by NickGerleman**
This creates versioned 0.64 docs from current docs, and sets to publish them as the latest.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows-samples/pull/409)

### CODE REVIEW

**Comment by asklar** [comment]
Please wait for https://github.com/microsoft/react-native-windows/pull/7393 and subsequent 0.64 port/generation

**Comment by NickGerleman** [comment]
> Please wait for [microsoft/react-native-windows#7393](https://github.com/microsoft/react-native-windows/pull/7393) and subsequent 0.64 port/generation

I can regenerate docs after that PR is submitted. Is this something that you think will be done by EOD?

**Comment by NickGerleman** [comment]
> I am going to add more changes in the next couple of days to this PR before it is ready for merge.

Judging by that bit in the original PR, I expect that we will need to continue iterating here. I would not like to hold the release on polishing API docs though.

**Comment by asklar** [comment]
@vmoroz any chance you might finish this by EOD? we'd like to snap 0.64.

**Comment by NickGerleman** [comment]
@asklar do you know why we would still be seeing unbroken errors after running the `fix-unbroken` script?

**Comment by asklar** [comment]
@jonthysell might know. I don't think the new exclusions fix-unbroken is adding are right, as there are missing ones.
You can delete those and just add `!versioned_docs/version-0.64/*-api-windows*.md` for the time being but we should fix fix-unbroken : )

**Comment by vmoroz** [comment]
> @vmoroz Vladimir Morozov (REDMOND) FTE any chance you might finish this by EOD? we'd like to snap 0.64.

No, it is not realistic. I need a couple of days. Let's add these docs later.

**Comment by NickGerleman** [comment]
Okay... I think this should be ready to merge now.

**Review by asklar — APPROVED** [review]

**Pull request merged**
