### PR TITLE
update home page, add macOS button, macOS instead of Mac

### PR DESCRIPTION
**Pull request by Simek**
This PR updates the home page and introduces the following changes:
* part of getting started text moved outside of the Windows button
* getting started buttons for Windows and macOS
* consistency in the platform naming - [`macOS`](https://www.apple.com/macos/what-is/) instead of `Mac` or `MacOS`
  * this includes site name and tagline in the `siteConfig.js`
  * "Mac" is the name of certain devices (hardware) made by Apple which are using macOS (AFAIK there is no such general counterpart word for the machines using Windows, PC is the close one, but in principal of definition Macs are Personal Computers too, usually PC term stick best to the Windows powered desktops)
* few small code simplifications

Apple naming may be confusing sometimes and I am not 100% sure if I handled the changes correctly, feel free to correct me. I'm fine to work further on this PR in any way needed.

### Test Plan
I have tested the height of header and display of the website in every `@media` break point on Win (Chrome, FF), macOS (Chrome, Safari) and iOS (Chrome, Safari).

### Preview
Screenshot 2020-05-13 at 22 12 40

### CODE REVIEW

**Comment by kikisaints** [comment]
Oh wow! this is a lot of work, thank you. I've actually just recently made a PR for a big visual update that is also adding call-to-action buttons for mac over on #97 - would you be able to merge your changes with that visual update as well?

**Comment by Simek** [comment]
Looking at your PR I can fairly say that this is a lot of work, ~x10 more LOC changes than me! 😄 And I should have check the content of other PRs not only read the titles, sorry for that!

I think that it will be easier for you to merge my changes in than the other way around, but I can also wait until your PR is merged and than resolve conflicts and update my code.

**Comment by Simek** [comment]
@kikisaints After a bit of struggle, the PR has been updated. I have used `GetStartedButton` component for the new buttons (as in original changeset) and I have also updated the code a bit and removed unused `GettingStartedActions` which was not a part of original PR.

**Comment by Simek** [comment]
BTW. @kikisaints There is an issue with the prev/next box at the bottom of the page after the latest visual update:
Annotation 2020-05-14 131016

Should I also apply fix for that in this PR?

**Comment by kikisaints** [comment]
> BTW. @kikisaints There is an issue with the prev/next box at the bottom of the page after the latest visual update:
> Annotation 2020-05-14 131016
> 
> Should I also apply fix for that in this PR?

Thanks! I missed this, obviously 😅 if you could I would love it if you could apply a fix.

**Comment by Simek** [comment]
I have just flipped the color variable, based on changes you have made in the previous PR, I hope that was the desirable change. (I was also thinking about using the navy blue from the buttons and header, but it might be too colourful):
Screenshot 2020-05-14 at 19 31 36

**Comment by kikisaints** [comment]
> I have just flipped the color variable, based on changes you have made in the previous PR, I hope that was the desirable change. (I was also thinking about using the navy blue from the buttons and header, but it might be too colourful):
> Screenshot 2020-05-14 at 19 31 36

I think you made the right call, thanks for the fix! Also just noticed I need to fix that blue BG to code blocks. :)

**Comment by Simek** [comment]
Is this PR ready from you point of view or should I change or update something else too?

**Pull request merged**
