### PR TITLE
Update hermes documentation for RNW65

### PR DESCRIPTION
**Pull request by mganandraj**
We are removing some limitations which we've worked in RN65.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows-samples/pull/477)

### CODE REVIEW

**Review by chrisglein — APPROVED** [review]

**Review by NickGerleman — APPROVED** [review]

**Comment by NickGerleman** [comment]
@mganandraj you might need to add a new word to the dictionary here https://github.com/microsoft/react-native-windows-samples/blob/master/.spelling

The output of the spell checker is meant to be colored, but this doesn't seem to come through on Github actions. @asklar do you know if there is a way we can fix that, or does this need checking out the repo and locally running.

**Comment by asklar** [comment]
> @mganandraj you might need to add a new word to the dictionary here https://github.com/microsoft/react-native-windows-samples/blob/master/.spelling
> 
> The output of the spell checker is meant to be colored, but this doesn't seem to come through on Github actions. @asklar do you know if there is a way we can fix that, or does this need checking out the repo and locally running?

@NickGerleman  I'm not sure why it isn't showing, it looks like AzDO doesn't yet fully support colors: https://github.com/microsoft/azure-pipelines-agent/issues/1569
but IIRC this works for tests so maybe support is partial? would be good to fix.

**Comment by NickGerleman** [comment]
@asklar Azure  pipelines has partial support, but this repo is on Github actions. Some libraries have fallback when not run in interactive mode (e.g spinners in CI), so theoretically the library could replace color, with something like an underline. 

I'd be curious about the robustness and dictionary completeness of other spell check solutions. I remember @Simek doing something pretty sophisticated for the RN website (IIRC including extra stuff like checking for insensitive content). Depending on false positive rate, a CR bot without PR enforcement could be a good way to achieve the same goal of catching spelling errors.

**Review by asklar — APPROVED** [review]

**Comment by Simek** [comment]
> I'd be curious about the robustness and dictionary completeness of other spell check solutions. I remember @Simek doing something pretty sophisticated for the RN website (IIRC including extra stuff like checking for insensitive content). Depending on false positive rate, a CR bot without PR enforcement could be a good way to achieve the same goal of catching spelling errors.

On the RN website we use Alex (https://github.com/get-alex/alex) in CI, but it's focused more on the insensitive, inconsiderate writing, not the typos or pure language-based spellchecking.

**Pull request merged**
