### PR TITLE
Add instructions to customize WinUI/SDK version

### PR DESCRIPTION
**Pull request by asklar**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows-samples/pull/465)

### CODE REVIEW

**Comment by dstaley** [comment]
@asklar I think it would be good to have a clear step-by-step for developers to follow to change the version of WinUI/SDK. Reading this, the only step it looks like I need to take is updating the `ExperimentalFlags.props` file. However, after doing that, my project is still using 2.3. The docs do say "Referencing the appropriate NuGet package so it gets downloaded", so I thought that might mean I need to update the Microsoft.UI.XAML NuGet package to 2.6, but doing so results in this error:

```
Cannot modify an evaluated object originating in an imported file "C:\WinUI26\node_modules\react-native-windows\PropertySheets\External\Microsoft.ReactNative.Uwp.CSharpApp.SourceReferences.targets".				
```

**Comment by asklar** [comment]
> @asklar Alexander Sklar FTE I think it would be good to have a clear step-by-step for developers to follow to change the version of WinUI/SDK. Reading this, the only step it looks like I need to take is updating the `ExperimentalFlags.props` file. However, after doing that, my project is still using 2.3. The docs do say "Referencing the appropriate NuGet package so it gets downloaded", so I thought that might mean I need to update the Microsoft.UI.XAML NuGet package to 2.6, but doing so results in this error:
> 
> ```
> Cannot modify an evaluated object originating in an imported file "C:\WinUI26\node_modules\react-native-windows\PropertySheets\External\Microsoft.ReactNative.Uwp.CSharpApp.SourceReferences.targets".				
> ```

@dstaley Is your project C# or C++? For C#, you only need to update the ExperimentalFeatures.props file.
For C++, you also need to update packages.config.
Can you clarify how you updated the package? VS will wreak havoc on the project if you do it from the UI, so you mustn't :)

**Comment by dstaley** [comment]
@asklar It's C#, and yup, I updated the NuGet package from Visual Studio 😬 After updating `ExperimentalFeatures.props`, are there any additional commands I need to run, or would `npx react-native run-windows` be it?

**Comment by asklar** [comment]
> @asklar Alexander Sklar FTE It's C#, and yup, I updated the NuGet package from Visual Studio 😬 After updating `ExperimentalFeatures.props`, are there any additional commands I need to run, or would `npx react-native run-windows` be it?

@dstaley  as long as you don't update it from VS, updating the props file is the only thing to do :)
VS nuget UI only knows how to update packages that have a certain format - i.e. versions are explicit instead of indirect via a property reference. Because RNW projects use properties to define versions, VS doesn't know what to do with that and just treats it as "this must be something weird", and adds a 2nd WinUI nuget package to the project, which will do all sorts of bad things. So: undo your changes to the csproj file, and just replace the props file and that should be it.

**Comment by dstaley** [comment]
@asklar Alrighty, gave that a shot, and this is what I got back:

```
This project references NuGet package(s) that are missing on this computer. Use 
NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\Unitrack\windows\packages\Microsoft.UI.Xaml.2.6.0\build\native\Microsoft.UI.Xaml.targets.
```

**Comment by asklar** [comment]
> @asklar Alrighty, gave that a shot, and this is what I got back:
> 
> ```
> This project references NuGet package(s) that are missing on this computer.
> Use NuGet Package Restore to download them.
> For more information, see http://go.microsoft.com/fwlink/?LinkID=322105.
> The missing file is C:\Unitrack\windows\packages\Microsoft.UI.Xaml.2.6.0\build\native\Microsoft.UI.Xaml.targets.
> ```

@dstaley ok I see my change to enable this functionality went in after we cut 0.64 (#7498). Can you check what version of RNW you are using? it should be at least 0.64.3 for this to work.

**Comment by dstaley** [comment]
@asklar Looks like I have v0.64.12

```
PS C:\Unitrack> yarn why react-native-windows
yarn why v1.22.5
[1/4] Why do we have the module "react-native-windows"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "react-native-windows@0.64.12"
info Has been hoisted to "react-native-windows"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "327.01MB"
info Disk size with unique dependencies: "398.15MB"
info Disk size with transitive dependencies: "464.12MB"
info Number of shared dependencies: 156
Done in 1.06s.
```

**Comment by asklar** [comment]
ok updated the instructions with the workaround - thanks for trying it out @dstaley !

**Review by AgneLukoseviciute — APPROVED** [review]

**Pull request merged**
