### PR TITLE
Add README Information on Cutting New Version Docs

### PR DESCRIPTION
**Pull request by chiaramooney**
**_Why_**
Add README information on cutting new version docs to clarify process and condense information into one location. 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows-samples/pull/476)

### CODE REVIEW

**Review by chrisglein — APPROVED** [review]

**Comment by NickGerleman** [comment]
I think these instructions might already be here https://github.com/microsoft/react-native-windows-samples/blob/master/websiteguide.md

**Comment by NickGerleman** [comment]
The old markdown isn't super discoverable though

**Comment by chiaramooney** [comment]
@NickGerleman  Ah I see. Yea I remember coming across this documentation a while ago and was searching for it this time around and couldn't remember where it was, so I definitely +1 the discoverability issue. Could we move this information to `website/README.md`?

**Comment by asklar** [comment]
I'm fine with merging the docs. The instructions you have here seem incomplete so I'd say remove those and paste the content from the website guide in here. @jonthysell in case he has any concerns with this plan.
Note that we also have some content in the code repo wiki, IIRC. And we also have the code repo docs folder.
We keep having this debate of discoverability of docs, whether they should be in the website, in the website repo as markdown only, the code repo as markdown, the wiki, Teams, OneNote, Sharepoint... Too many options.

**Pull request merged**
