### PR TITLE
Upgrade AppServiceDemo to RNW 0.67

### LINKED ISSUE #586: AppServiceDemo on rn-windows 0.66.3 does not build
### Sample

AppServiceDemo

### Problem Description

AppServiceDemo on `rn-windows 0.66.3` does not build. I get error `Payload contains two or more files with the same destination path 'Microsoft.UI.Xaml.Markup.winmd'`  

I have same problem with my app that is React Native Windows 0.66.2 UWP C# and Win32 console solution.

See AppServiceDemo example app ported into 0.66.3 below.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	APPX1112	Payload contains two or more files with the same destination path 'Microsoft.UI.Xaml.Markup.winmd', but they have different content. Source files: 
C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.UI.Xaml.Markup.winmd
C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.UI.Xaml.Markup.winmd	appservicedemo.Package	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	1946	

```

### Steps To Reproduce

Use AppServiceDemo and port it into rn-windows 0.66.3

### Expected Results

_No response_

### CLI version

6.0.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 21.61 GB / 31.90 GB
  Binaries:
    Node: 12.22.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31624.102 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.1 => 0.66.1
    react-native-windows: 0.66.3 => 0.66.3
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

_No response_

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019 16.11.2

### Build Configuration

Debug

### PR DESCRIPTION
**Pull request by jonthysell**
This PR updates the AppServiceDemo to RNW 0.67.

This included:

1.  Bumping the versions in packages.json using the UpgradeSmokeTest script.
2. Re-intializing both the AppServiceDemo app and ReactNativeAppServiceModule lib projects with
   `react-native-windows-init`.
3. Re-applying the native changes from the original code to the new template files.

Closes #586

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-windows-samples/pull/652)

### CODE REVIEW

**Comment by tero-paananen** [comment]
> @tero-paananen

Thank you! I will check your changes carefully!

**Comment by tero-paananen** [comment]
One note. Reason why this build now is that it depends now `<TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.19041.0</TargetPlatformVersion>`  if you add some module whose version is different (for example community module) example does not build anymore, i think.

**Comment by jonthysell** [comment]
> One note. Reason why this build now is that it depends now `<TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.19041.0</TargetPlatformVersion>` if you add some module whose version is different (for example community module) example does not build anymore, i think. Is there some difference if included module is implemented by c# or c++ i am not sure.

Since it's an override for a blank value, unless the community module specifically hardcodes a value, the app developer should be able to override the value by hardcoding it in their ExperimentalFeatures.props file, so that all RNW projects pick it up.

Now obviously that might be a problem if you have projects that don't follow the template (whether because they're very old or didn't ever follow the template) but then you can always set the value in an appropriately placed Directory.Build.props file.

**Review by TatianaKapos — APPROVED** [review]
LGTM! We should add some Upgrade Steps in the Readme at some point

**Pull request merged**
